# Generated by Django 5.2.9 on 2025-12-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exports", "0018_auto_20210219_1943"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardingDestination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "api_url",
                    models.URLField(
                        help_text="API endpoint URL where data will be sent",
                        max_length=500,
                    ),
                ),
                (
                    "api_username",
                    models.CharField(
                        blank=True,
                        help_text="Username for basic authentication",
                        max_length=100,
                    ),
                ),
                (
                    "api_password",
                    models.CharField(
                        blank=True,
                        help_text="Password for basic authentication",
                        max_length=200,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardingConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "query",
                    models.TextField(
                        help_text="SQL query to execute. Must return exactly one row with one field containing the payload (typically JSON)."
                    ),
                ),
                (
                    "query_params",
                    models.TextField(
                        blank=True,
                        help_text="Query parameters (one per line). Mapped to :param1, :param2, etc. in the query.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exports.exportdatabase",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        blank=True,
                        help_text="Scheduling configuration for automatic forwarding.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.schedule",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forwarding.forwardingdestination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForwardingRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the forward actually started running. It may have been created/queued earlier.",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_from_ui", models.BooleanField(default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("log", models.TextField(blank=True, null=True)),
                (
                    "forwarding_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="forwarding.forwardingconfig",
                    ),
                ),
                (
                    "forwarding_config_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reversion.version",
                    ),
                ),
                (
                    "triggering_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
