# Generated by Django 5.2.9 on 2025-12-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forwarding", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name='forwardingrun',
            old_name='base_forwarding_config',
            new_name='forwarding_config',
        ),
    ]
