# Generated by Django 5.2.12 on 2026-03-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_remove_database_owner"),
        ("forwarding", "0002_update_database_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forwardingconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="forwardingdestination",
            name="owner",
        ),
        migrations.AlterField(
            model_name="forwardingconfig",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="db.database",
            ),
        ),
        migrations.AlterField(
            model_name="forwardingconfig",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="forwarding.forwardingdestination",
            ),
        ),
    ]
