# Generated by Django 5.2.9 on 2025-12-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forwarding", "0002_rename_base_forwarding_config_to_forwarding_config"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forwardingconfig",
            name="is_paused",
        ),
        migrations.AlterField(
            model_name="forwardingconfig",
            name="schedule",
            field=models.OneToOneField(
                blank=True,
                help_text="Scheduling configuration for automatic forwarding.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="forwardingrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
    ]
