# Generated by Django 5.2.14 on 2026-05-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forwarding", "0006_encrypt_existing_api_passwords"),
    ]

    operations = [
        migrations.AddField(
            model_name="forwardingdestination",
            name="http_method",
            field=models.CharField(
                choices=[("POST", "POST"), ("PUT", "PUT")],
                default="POST",
                help_text="HTTP method used to send data to the destination",
                max_length=7,
            ),
        ),
    ]
