dist: jammy
language: python
python:
  - "3.10"
services:
  - postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE=commcare_sync.settings_travis
before_install:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - uv sync
jobs:
  include:
    - name: "Linter"
      python:
        - "3.10"
      install:
        - uv pip install flake8
      script:
        - uv run flake8 commcare_sync/
    - name: "Django Test - Python 3.10"
      python:
        - "3.10"
      before_script:
        - psql -c 'create database commcare_sync_test;' -U postgres
        - cp .travis/settings_travis.py commcare_sync
      install:
        - uv sync --frozen
      script:
        - uv run manage.py test
