services:
  db:
    image: postgres
    ports:
      - "5433:5432"  # Don't clash host port with commcare-hq
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=commcare_sync
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    ports:
      - "6380:6379"  # Don't clash host port with commcare-hq
    # persistent storage
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uv run manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uv run celery -A commcare_sync worker -l INFO -B
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
