FROM python:3.8-buster
ENV PYTHONUNBUFFERED=1

RUN \
  echo "deb https://deb.nodesource.com/node_14.x buster main" > /etc/apt/sources.list.d/nodesource.list && \
  wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  apt-get update && \
  apt-get install -yqq nodejs

# copy code files
RUN mkdir /code
WORKDIR /code

COPY requirements requirements/
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /code/
