[project]
name = "commcare-sync"
version = "0.1.0"
description = "CommCare Sync simplifies the management of your CommCare data pipeline"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "Django~=5.2",
    "django-allauth",
    "psycopg2-binary",
    "django-anymail[mailgun]",  # email services
    "celery-progress",
    "celery[redis]",
    "django-celery-beat",
    "django-reversion>=5.0.4",
    "commcare-export==1.13.0",
    "pyopenssl>=20.0.1",  # here to force upgrades of commcare-export dependencies
    "db-query-fwd",
]

[project.optional-dependencies]
prod = [
    "gunicorn[eventlet]",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    {include-group = "test"},
    "pip-tools",
]
test = [
    "django-stubs",
    "mypy",
    "pytest",
    "pytest-django",
    "pytest-unmagic",
    "ruff",
    "time-machine",
]

[tool.uv.sources]
db-query-fwd = { git = "https://github.com/dimagi/db-query-fwd.git" }

[tool.mypy]
disallow_incomplete_defs = true
ignore_missing_imports = true
plugins = [
    "mypy_django_plugin.main",
]
disable_error_code = [
    "var-annotated",
]

[tool.django-stubs]
django_settings_module = "commcare_sync.settings"

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "commcare_sync.settings"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
