# Generated by Django 2.1.7 on 2019-03-21 12:18
from django.conf import settings
from django.db import migrations


def create_site(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    pass
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get_or_create(
        id=settings.SITE_ID
    )[0]
    site.domain = settings.PROJECT_METADATA['URL']
    site.name = settings.PROJECT_METADATA['NAME']
    site.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_site),
    ]
