# Generated by Django 5.2.14 on 2026-07-25 15:55

import apps.schedules.mixin
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("db", "0002_remove_database_owner"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interval", "Every N minutes/hours/days"),
                            ("weekly", "Weekly on specific days"),
                            ("monthly", "Monthly on specific day"),
                            ("quarterly", "Quarterly"),
                            ("semi-annually", "Semi-annually (twice per year)"),
                            ("annually", "Annually"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "first_run_date",
                    models.DateField(
                        blank=True, help_text="Don't run before this date", null=True
                    ),
                ),
                (
                    "first_run_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time of day for first/recurring runs",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for scheduled runs (e.g., 'America/New_York', 'UTC')",
                        max_length=63,
                    ),
                ),
                (
                    "interval_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of time units between runs",
                        null=True,
                    ),
                ),
                (
                    "interval_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        help_text="Time unit for interval",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday",
                        validators=[apps.schedules.mixin._validate_days_of_week],
                    ),
                ),
                (
                    "schedule_enabled",
                    models.BooleanField(
                        default=True, help_text="Uncheck to pause scheduled runs"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "materialized_views",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of materialized views (schema.view_name) to refresh in order",
                    ),
                ),
                (
                    "concurrently",
                    models.BooleanField(
                        default=False,
                        help_text="Use REFRESH MATERIALIZED VIEW CONCURRENTLY to avoid locking the view during refresh. Requires a unique index on each view.",
                    ),
                ),
                (
                    "database",
                    models.ForeignKey(
                        help_text="PostgreSQL database connection",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="db.database",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RefreshRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the run actually started. It may have been created/queued earlier.",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_from_ui", models.BooleanField(default=None, null=True)),
                ("log", models.TextField(blank=True, null=True)),
                ("view_results", models.JSONField(default=dict)),
                (
                    "refresh_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="refreshes.refreshconfig",
                    ),
                ),
                (
                    "refresh_config_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reversion.version",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
