# Generated by Django 5.2.14 on 2026-08-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refreshes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refreshrun",
            old_name="refresh_config",
            new_name="config",
        ),
        migrations.RenameField(
            model_name="refreshrun",
            old_name="refresh_config_version",
            new_name="config_version",
        ),
    ]
