# Generated by Django 5.2.12 on 2026-03-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_remove_database_owner"),
        ("refreshes", "0002_update_database_fk"),
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshconfig",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="refreshconfig",
            name="database",
            field=models.ForeignKey(
                help_text="PostgreSQL database connection",
                on_delete=django.db.models.deletion.PROTECT,
                to="db.database",
            ),
        ),
        migrations.AlterField(
            model_name="refreshrun",
            name="refresh_config_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reversion.version",
            ),
        ),
    ]
