# Generated by Django 5.2.12 on 2026-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refreshes", "0003_remove_refreshconfig_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refreshrun",
            old_name="triggering_user",
            new_name="triggered_by",
        ),
        migrations.AlterField(
            model_name="refreshrun",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the run actually started. It may have been created/queued earlier.",
                null=True,
            ),
        ),
    ]
