# Generated by Django 5.2.14 on 2026-09-26 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refreshes', '0003_add_timeout_status'),
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refreshrun',
            index=models.Index(fields=['status', 'started_at'], name='refreshes_r_status_20bea4_idx'),
        ),
    ]
