# Generated by Django 5.2.14 on 2026-09-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refreshes', '0004_add_run_reap_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshrun',
            name='retry_of',
            field=models.OneToOneField(blank=True, help_text='The timed-out run that this run retries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry', to='refreshes.refreshrun'),
        ),
    ]
