# Generated by Django 5.2.12 on 2026-03-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="database",
            name="owner",
        ),
    ]
