# Generated by Django 3.0.5 on 2020-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commcareproject',
            unique_together={('server', 'domain')},
        ),
    ]
