# Generated by Django 3.0.5 on 2020-05-13 08:53

from django.db import migrations


def create_default_commcare(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CommCareServer = apps.get_model('commcare', 'CommCareServer')
    # create default server if it doesn't exist yet.
    CommCareServer.objects.get_or_create()


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_commcare, migrations.RunPython.noop),
    ]


