# Generated by Django 3.0.5 on 2020-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0002_create_commcare_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcareserver',
            name='url',
            field=models.CharField(default='https://www.commcarehq.org', max_length=100, unique=True),
        ),
    ]
