# Generated by Django 3.0.5 on 2020-05-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0002_auto_20200504_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commcareaccount',
            unique_together={('server', 'username')},
        ),
    ]
