# Generated by Django 3.0.5 on 2020-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0003_auto_20200513_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcareaccount',
            name='username',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commcareproject',
            name='domain',
            field=models.CharField(help_text='Your CommCare domain (available from the URL)', max_length=100),
        ),
    ]
