# Generated by Django 3.0.5 on 2020-05-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0004_auto_20200513_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commcareaccount',
            name='api_key',
            field=models.CharField(help_text='Your API key is available under "My Account Settings" in CommCare.', max_length=40),
        ),
        migrations.AlterField(
            model_name='commcareaccount',
            name='username',
            field=models.EmailField(help_text='The email address you use to sign into CommCare HQ', max_length=100),
        ),
    ]
