# Generated by Django 3.0.5 on 2020-04-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommCareAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommCareProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommCareServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='CommCare HQ', max_length=100)),
                ('url', models.CharField(default='https://www.commcarehq.org/', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_string', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_file', models.FileField(blank=True, null=True, upload_to='export-configs/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.CommCareAccount')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.ExportDatabase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.CommCareProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commcareproject',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.CommCareServer'),
        ),
        migrations.AddField(
            model_name='commcareaccount',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.CommCareServer'),
        ),
    ]
