# Generated by Django 3.0.5 on 2020-05-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commcare', '0005_auto_20200514_1153'),
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiProjectExportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('config_file', models.FileField(upload_to='export-configs/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commcare.CommCareAccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.ExportDatabase')),
                ('projects', models.ManyToManyField(to='commcare.CommCareProject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
