# Generated by Django 3.0.5 on 2020-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_exportdatabase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportconfig',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
