# Generated by Django 3.0.5 on 2020-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_multiprojectexportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportconfig',
            name='extra_args',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiprojectexportconfig',
            name='extra_args',
            field=models.TextField(blank=True, null=True),
        ),
    ]
