# Generated by Django 3.0.5 on 2020-04-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_exportconfig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('failed', 'failed')], default='started', max_length=10)),
                ('export_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exports.ExportConfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
