# Generated by Django 3.0.5 on 2020-05-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0004_exportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportrun',
            name='export_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='exports.ExportConfig'),
        ),
    ]
