# Generated by Django 3.0.5 on 2020-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_auto_20200501_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportconfig',
            name='config_file',
            field=models.FileField(upload_to='export-configs/'),
        ),
    ]
