# Generated by Django 3.0.5 on 2020-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_auto_20200619_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportconfig',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Pausing an export will disable automatic syncing.'),
        ),
        migrations.AddField(
            model_name='multiprojectexportconfig',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Pausing an export will disable automatic syncing.'),
        ),
    ]
