# Generated by Django 3.0.5 on 2020-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0007_auto_20200706_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='triggered_from_ui',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='triggered_from_ui',
            field=models.NullBooleanField(default=None),
        ),
    ]
