# Generated by Django 3.0.5 on 2020-07-21 08:39

from django.db import migrations, models

NEW_INDEX_NAME = (
    'exports_multiprojectpartialexportrun_export_config_id_bcc53671'
    'myapp_mymodel_myfield_othermodel_id_0f4cfc54'
)


def rename_index(apps, schema_editor):
    # Rename the auto-generated FK index to workaround this bug
    # https://code.djangoproject.com/ticket/23577#comment:17 (RenameModel
    # doesn't rename it, so the next migration's model of the original name
    # collides with it). Uses schema_editor.rename_index directly, since the
    # declarative RenameIndex operation only supports indexes registered in
    # Meta.indexes, not auto-generated FK indexes. This is portable: ALTER
    # INDEX RENAME on PostgreSQL, drop/recreate on SQLite.
    model = apps.get_model('exports', 'MultiProjectPartialExportRun')
    # `_constraint_names` is a private schema_editor API (all built-in Django
    # backends implement it, and the declarative `RenameIndex` operation
    # relies on the same method for its `old_fields` form). If a future
    # Django upgrade removes or changes it, this call needs revisiting.
    old_name = schema_editor._constraint_names(
        model,
        column_names=[model._meta.get_field('export_config').column],
        index=True,
        unique=False,
    )[0]
    old_index = models.Index(fields=['export_config'], name=old_name)
    new_index = models.Index(fields=['export_config'], name=NEW_INDEX_NAME)
    schema_editor.rename_index(model, old_index, new_index)


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0005_auto_20200514_1153'),
        ('exports', '0008_auto_20200721_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiProjectExportRun',
            new_name='MultiProjectPartialExportRun',
        ),
        # No reverse_code: the original RunSQL had no reverse_sql either, so
        # unapplying this migration was already unsupported (raises
        # NotImplementedError). Leaving reverse_code unset preserves that;
        # passing RunPython.noop would make it falsely reversible, silently
        # leaving the index renamed while RenameModel's automatic reverse
        # renames the model back.
        migrations.RunPython(rename_index),
    ]
