# Generated by Django 3.0.5 on 2020-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0010_auto_20200721_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the export actually started running. It may have been created/queued earlier.', null=True),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the export actually started running. It may have been created/queued earlier.', null=True),
        ),
        migrations.AddField(
            model_name='multiprojectpartialexportrun',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the export actually started running. It may have been created/queued earlier.', null=True),
        ),
        migrations.AlterField(
            model_name='exportrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=10),
        ),
        migrations.AlterField(
            model_name='multiprojectexportrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=10),
        ),
        migrations.AlterField(
            model_name='multiprojectpartialexportrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=10),
        ),
    ]
