# Generated by Django 3.0.5 on 2020-07-21 11:30

from django.db import migrations


def populate_multi_export_runs(apps, schema_editor):
    # for the multi-project exports, create a stub MultiProjectExportRun object
    # and move all the partial runs under that
    MultiProjectExportConfig = apps.get_model('exports', 'MultiProjectExportConfig')
    MultiProjectExportRun = apps.get_model('exports', 'MultiProjectExportRun')
    MultiProjectPartialExportRun = apps.get_model('exports', 'MultiProjectPartialExportRun')
    for multi_export in MultiProjectExportConfig.objects.all():
        # import pdb; pdb.set_trace()
        migrate_run = MultiProjectExportRun.objects.create(export_config=multi_export)
        for partial_run in MultiProjectPartialExportRun.objects.filter(export_config=multi_export):
            partial_run.parent_run = migrate_run
            partial_run.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0011_auto_20200721_1110'),
    ]

    operations = [
        migrations.RunPython(populate_multi_export_runs),
    ]
