# Generated by Django 3.0.5 on 2020-09-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0013_auto_20200721_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportconfig',
            name='batch_size',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='multiprojectexportconfig',
            name='batch_size',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='exportrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('completed', 'completed'), ('failed', 'failed'), ('multiple', 'multiple statuses'), ('skipped', 'skipped')], default='queued', max_length=10),
        ),
        migrations.AlterField(
            model_name='multiprojectexportrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('completed', 'completed'), ('failed', 'failed'), ('multiple', 'multiple statuses'), ('skipped', 'skipped')], default='queued', max_length=10),
        ),
        migrations.AlterField(
            model_name='multiprojectpartialexportrun',
            name='parent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partial_runs', to='exports.MultiProjectExportRun'),
        ),
        migrations.AlterField(
            model_name='multiprojectpartialexportrun',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('started', 'started'), ('completed', 'completed'), ('failed', 'failed'), ('multiple', 'multiple statuses'), ('skipped', 'skipped')], default='queued', max_length=10),
        ),
    ]
