# Generated by Django 3.0.5 on 2020-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0014_auto_20200902_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='run_config_file',
            field=models.FileField(null=True, upload_to='export-configs/'),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='run_config_file',
            field=models.FileField(null=True, upload_to='export-configs/'),
        )
    ]
