# Generated by Django 3.0.5 on 2020-12-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('exports', '0014_auto_20200902_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrun',
            name='export_config',
        ),
        migrations.RemoveField(
            model_name='multiprojectexportrun',
            name='export_config',
        ),
        migrations.AddField(
            model_name='exportrun',
            name='base_export_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='exports.ExportConfig'),
        ),
        migrations.AddField(
            model_name='exportrun',
            name='export_config_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reversion.Version'),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='base_export_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='exports.MultiProjectExportConfig'),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='export_config_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reversion.Version'),
        )
    ]
