# Generated by Django 3.0.5 on 2021-01-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exports', '0014_auto_20200902_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='triggering_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='triggering_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiprojectpartialexportrun',
            name='triggering_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exportconfig',
            name='batch_size',
            field=models.PositiveIntegerField(default=500, help_text='How many cases to fetch at a time from CommCare. Try increasing this number if your export gets stuck.'),
        ),
        migrations.AlterField(
            model_name='multiprojectexportconfig',
            name='batch_size',
            field=models.PositiveIntegerField(default=500, help_text='How many cases to fetch at a time from CommCare. Try increasing this number if your export gets stuck.'),
        ),
    ]
