# Generated by Django 3.0.5 on 2020-12-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('exports', '0015_auto_20210114_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportrun',
            old_name='export_config',
            new_name='base_export_config',
        ),
        migrations.RenameField(
            model_name='multiprojectexportrun',
            old_name='export_config',
            new_name='base_export_config',
        ),
        migrations.AddField(
            model_name='exportrun',
            name='export_config_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reversion.Version'),
        ),
        migrations.AddField(
            model_name='multiprojectexportrun',
            name='export_config_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reversion.Version'),
        )
    ]
