# Generated by Django 3.1.6 on 2021-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0017_auto_20210217_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrun',
            name='triggered_from_ui',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='multiprojectexportrun',
            name='triggered_from_ui',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='multiprojectpartialexportrun',
            name='triggered_from_ui',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
