# Generated by Django 5.2.12 on 2026-03-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commcare", "0007_encrypt_existing_api_keys"),
        ("db", "0002_remove_database_owner"),
        ("exports", "0021_remove_exportdatabase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportconfig",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="multiprojectexportconfig",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="exportconfig",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commcare.commcareaccount",
            ),
        ),
        migrations.AlterField(
            model_name="exportconfig",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="db.database"
            ),
        ),
        migrations.AlterField(
            model_name="exportconfig",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commcare.commcareproject",
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectexportconfig",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="commcare.commcareaccount",
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectexportconfig",
            name="database",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="db.database"
            ),
        ),
    ]
