# Generated by Django 5.2.12 on 2026-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0022_remove_exportconfig_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exportrun",
            old_name="triggering_user",
            new_name="triggered_by",
        ),
        migrations.RenameField(
            model_name="multiprojectexportrun",
            old_name="triggering_user",
            new_name="triggered_by",
        ),
        migrations.RenameField(
            model_name="multiprojectpartialexportrun",
            old_name="triggering_user",
            new_name="triggered_by",
        ),
        migrations.AlterField(
            model_name="exportrun",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the run actually started. It may have been created/queued earlier.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("multiple", "Multiple statuses"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectexportrun",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the run actually started. It may have been created/queued earlier.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectexportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("multiple", "Multiple statuses"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectpartialexportrun",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the run actually started. It may have been created/queued earlier.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectpartialexportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("multiple", "Multiple statuses"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
    ]
