# Generated by Django 5.2.14 on 2026-07-25 15:55

import apps.schedules.mixin
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0023_rename_triggering_user_exportrun_triggered_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportconfig",
            name="is_paused",
        ),
        migrations.RemoveField(
            model_name="exportconfig",
            name="time_between_runs",
        ),
        migrations.RemoveField(
            model_name="multiprojectexportconfig",
            name="is_paused",
        ),
        migrations.RemoveField(
            model_name="multiprojectexportconfig",
            name="time_between_runs",
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday",
                validators=[apps.schedules.mixin._validate_days_of_week],
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="first_run_date",
            field=models.DateField(
                blank=True, help_text="Don't run before this date", null=True
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="first_run_time",
            field=models.TimeField(
                default=datetime.time(0, 0),
                help_text="Time of day for first/recurring runs",
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="interval_unit",
            field=models.CharField(
                blank=True,
                choices=[("minutes", "Minutes"), ("hours", "Hours"), ("days", "Days")],
                help_text="Time unit for interval",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="interval_value",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of time units between runs", null=True
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="next_run_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="schedule_enabled",
            field=models.BooleanField(
                default=True, help_text="Uncheck to pause scheduled runs"
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="schedule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interval", "Every N minutes/hours/days"),
                    ("weekly", "Weekly on specific days"),
                    ("monthly", "Monthly on specific day"),
                    ("quarterly", "Quarterly"),
                    ("semi-annually", "Semi-annually (twice per year)"),
                    ("annually", "Annually"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Timezone for scheduled runs (e.g., 'America/New_York', 'UTC')",
                max_length=63,
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday",
                validators=[apps.schedules.mixin._validate_days_of_week],
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="first_run_date",
            field=models.DateField(
                blank=True, help_text="Don't run before this date", null=True
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="first_run_time",
            field=models.TimeField(
                default=datetime.time(0, 0),
                help_text="Time of day for first/recurring runs",
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="interval_unit",
            field=models.CharField(
                blank=True,
                choices=[("minutes", "Minutes"), ("hours", "Hours"), ("days", "Days")],
                help_text="Time unit for interval",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="interval_value",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of time units between runs", null=True
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="next_run_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="schedule_enabled",
            field=models.BooleanField(
                default=True, help_text="Uncheck to pause scheduled runs"
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="schedule_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interval", "Every N minutes/hours/days"),
                    ("weekly", "Weekly on specific days"),
                    ("monthly", "Monthly on specific day"),
                    ("quarterly", "Quarterly"),
                    ("semi-annually", "Semi-annually (twice per year)"),
                    ("annually", "Annually"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Timezone for scheduled runs (e.g., 'America/New_York', 'UTC')",
                max_length=63,
            ),
        ),
    ]
