# Generated by Django 5.2.14 on 2026-08-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0024_remove_exportconfig_is_paused_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exportrun",
            old_name="base_export_config",
            new_name="config",
        ),
        migrations.RenameField(
            model_name="exportrun",
            old_name="export_config_version",
            new_name="config_version",
        ),
        migrations.RenameField(
            model_name="multiprojectexportrun",
            old_name="base_export_config",
            new_name="config",
        ),
        migrations.RenameField(
            model_name="multiprojectexportrun",
            old_name="export_config_version",
            new_name="config_version",
        ),
    ]
