# Generated by Django 5.2.14 on 2026-08-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0025_rename_run_config_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("timeout", "Timed out"),
                    ("multiple", "Multiple statuses"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectexportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("timeout", "Timed out"),
                    ("multiple", "Multiple statuses"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectpartialexportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("timeout", "Timed out"),
                    ("multiple", "Multiple statuses"),
                ],
                default="queued",
                max_length=10,
            ),
        ),
    ]
