# Generated by Django 5.2.14 on 2026-09-26 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commcare', '0007_encrypt_existing_api_keys'),
        ('exports', '0026_add_timeout_status'),
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exportrun',
            index=models.Index(fields=['status', 'started_at'], name='exports_exp_status_2616eb_idx'),
        ),
        migrations.AddIndex(
            model_name='multiprojectexportrun',
            index=models.Index(fields=['status', 'started_at'], name='exports_mul_status_4db0de_idx'),
        ),
        migrations.AddIndex(
            model_name='multiprojectpartialexportrun',
            index=models.Index(fields=['status', 'started_at'], name='exports_mul_status_15dad1_idx'),
        ),
    ]
