# Generated by Django 5.2.14 on 2026-07-31 20:55

import apps.schedules.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0026_remove_exportconfig_is_paused_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportconfig",
            name="periodic_task",
        ),
        migrations.RemoveField(
            model_name="multiprojectexportconfig",
            name="periodic_task",
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="next_run_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="exportconfig",
            name="schedule_enabled",
            field=models.BooleanField(
                default=True, help_text="Uncheck to pause scheduled runs"
            ),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="next_run_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="multiprojectexportconfig",
            name="schedule_enabled",
            field=models.BooleanField(
                default=True, help_text="Uncheck to pause scheduled runs"
            ),
        ),
        migrations.AlterField(
            model_name="exportconfig",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday",
                validators=[apps.schedules.mixin._validate_days_of_week],
            ),
        ),
        migrations.AlterField(
            model_name="multiprojectexportconfig",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday",
                validators=[apps.schedules.mixin._validate_days_of_week],
            ),
        ),
    ]
